# Config file for drone simulation and field deployment

# Global simulation parameters
simulation:
  time_warp: 1
  number_of_drones: 3
  ardupilot_ip: "0.0.0.0"
  ardupilot_protocol: "udp"
  home_altitude: 106.1
  fdm_port_in_default: 9002
  ardupilot_port_default: 14550

# Field deployment parameters
field:
  ardupilot_ip: "ttySAC0" # serial port
  ardupilot_port: "115200" # baudrate
  ardupilot_protocol: "serial"

moos:
  defaultPorts:
    DB: 9000
    PSHARE: 9200
  datum:
    lat: 63.3975168
    lon: 10.1435321

drones:
  - name: "skywalker"
    color: "orange"
    start_orientaton_moos: # +x is east, +y is north [m] !!MOOS seems to double he distance,  so 50m east is a distance of 100 in MOOS!!
      x: 0
      y: 0
      hdg: 46 # deg
    # simulation: # Can be automated away (for now it is hardcoded)
    #   ardupilot_port: 14550
    #   fdm_port_in: 9002

  - name: "skyfollower"
    color: "brown"
    start_orientaton_moos: # +x is east, +y is north [m]
      x: -100
      y: -5
      hdg: 36 # deg
    # simulation:
    #   ardupilot_port: 14560
    #   fdm_port_in: 9012

  - name: "skytrailer"
    color: "purple"
    start_orientaton_moos: # +x is east, +y is north [m]
      x: 100
      y: -5
      hdg: 56 # deg
    # simulation:
    #   ardupilot_port: 14570
    #   fdm_port_in: 9022
